{% set name = "pandoc-plot" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LaurentRDC/{{ name }}/releases/download/{{ version }}/pandoc-plot-Windows-x86_64.zip  # [win]
  sha256: 338dd4f3ba2d7e2f3e8114d4e9bb7ba2bf3a5803bd68971333e53a65be2df075  # [win]

  # url: https://github.com/LaurentRDC/{{ name }}/releases/download/{{ version }}/pandoc-plot-Linux-x86_64-static.zip  # [linux64]
  # sha256: f716c87f99468d721cfde74f035fd383c70e054eafb26bf9456cbf8e82c81666  # [linux64]

  url: https://github.com/LaurentRDC/{{ name }}/releases/download/{{ version }}/pandoc-plot-macOS-x86_64.zip  # [osx]
  sha256: bf433c45229f910a4f267ab7145c0dcf6d772ad7a296974ebe99b303b21df004  # [osx]

build:
  skip: true  # [linux]
  number: 0

requirements:
  run:
    - pandoc >=2.11,<2.18

test:
  commands:
    - pandoc-plot --version
    - pandoc-plot --help

about:
  home: https://github.com/LaurentRDC/pandoc-plot
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Render and include figures in Pandoc documents using your plotting toolkit of choice
  description: |
    pandoc-plot turns code blocks present in your documents (Markdown, LaTeX, etc.) 
    into embedded figures, using your plotting toolkit of choice, including Matplotlib, ggplot2, 
    MATLAB, Mathematica, and more.
  doc_url: https://github.com/LaurentRDC/pandoc-plot/
  dev_url: https://github.com/LaurentRDC/pandoc-plot/

extra:
  recipe-maintainers:
    - LaurentRDC
